### ISSUE TITLE
Missing class with 0.8

### ISSUE THREAD

**Issue by tmortagne** [schrepfler/jira-maven-plugin#59] opened 2018-10-29 10:06 UTC
I get the following when upgrading the plugin from 0.7 to 0.8:

    [ERROR] Failed to execute goal net.sigmalab.maven.plugins:jira-maven-plugin:0.8:release-jira-version (default) on project xwiki-commons-tool-webjar-handlers: Execution default of goal net.sigmalab.maven.plugins:jira-maven-plugin:0.8:release-jira-version failed: A required class was missing while executing net.sigmalab.maven.plugins:jira-maven-plugin:0.8:release-jira-version: com/atlassian/fugue/Effect

Sounds like bad or missing dependency in the plugin.

Maven verison: 3.5.4
Java verison: 1.8

**Comment by schrepfler** [comment] 2018-10-29 10:11
I think it's related with this https://community.atlassian.com/t5/Answers-Developer-Questions/ClassNotFoundException-com-atlassian-fugue-Effect-after-upgrade/qaq-p/571630 

I didn't know Atlassian has these helpers for Guava https://bitbucket.org/atlassian/fugue/src

@dgrierso can you take a look at this?

**Comment by tmortagne** [comment] 2018-10-29 10:28
Would be nice to also explain why it's required since it's very unusual to have a plugin which does not come with all the dependencies it needs.

**Comment by schrepfler** [comment] 2018-10-29 18:37
That's a good point, if the dependency is declared I would expect it's downloaded by default by the plugin and kept separately by maven on the plugin runtime classpath. Is there a reason why we don't bundle it with the rest of the dependencies for the plugin? https://github.com/schrepfler/jira-maven-plugin/blob/develop/pom.xml#L133

**Comment by dgrierso** [comment] 2018-10-30 22:29
@schrepfler : We don't bundle any dependencies with this jar - that's what the `<dependencies>` section of the pom.xml specifies.

If you explode the built jar you'll find that there are no other jar's included within it :

    iMac:target dgrierso$ jar tvf jira-maven-plugin-0.9-SNAPSHOT.jar 
        99 Tue Oct 30 22:16:06 GMT 2018 META-INF/MANIFEST.MF
         0 Tue Oct 30 22:16:06 GMT 2018 META-INF/
         0 Tue Oct 30 22:15:36 GMT 2018 net/
         0 Tue Oct 30 22:15:36 GMT 2018 net/sigmalab/
         0 Tue Oct 30 22:15:36 GMT 2018 net/sigmalab/maven/
         0 Tue Oct 30 22:15:36 GMT 2018 net/sigmalab/maven/plugin/
         0 Tue Oct 30 22:15:38 GMT 2018 net/sigmalab/maven/plugin/jira/
         0 Tue Oct 30 22:15:36 GMT 2018 net/sigmalab/maven/plugin/jira/formats/
         0 Tue Oct 30 22:15:44 GMT 2018 META-INF/maven/
         0 Tue Oct 30 22:15:44 GMT 2018 META-INF/maven/net.sigmalab.maven.plugins/
         0 Tue Oct 30 22:15:44 GMT 2018 META-INF/maven/net.sigmalab.maven.plugins/jira-maven-plugin/
         0 Tue Oct 30 22:15:32 GMT 2018 META-INF/plexus/
      5513 Tue Oct 30 22:15:38 GMT 2018 net/sigmalab/maven/plugin/jira/ReleaseVersionMojo.class
      2431 Tue Oct 30 22:15:36 GMT 2018 net/sigmalab/maven/plugin/jira/formats/PlainTextGenerator.class
      6167 Tue Oct 30 22:15:36 GMT 2018 net/sigmalab/maven/plugin/jira/AbstractJiraMojo.class
     17387 Tue Oct 30 22:15:50 GMT 2018 META-INF/maven/net.sigmalab.maven.plugins/jira-maven-plugin/plugin-help.xml
      2709 Tue Oct 30 22:15:36 GMT 2018 net/sigmalab/maven/plugin/jira/formats/Generator.class
      5163 Tue Oct 30 22:15:38 GMT 2018 net/sigmalab/maven/plugin/jira/CreateNewVersionMojo.class
     18269 Tue Oct 30 22:12:30 GMT 2018 META-INF/maven/net.sigmalab.maven.plugins/jira-maven-plugin/pom.xml
      2570 Tue Oct 30 22:15:36 GMT 2018 net/sigmalab/maven/plugin/jira/formats/HtmlGenerator.class
      8368 Tue Oct 30 22:15:38 GMT 2018 net/sigmalab/maven/plugin/jira/GenerateReleaseNotesMojo.class
      2036 Tue Oct 30 22:15:32 GMT 2018 META-INF/plexus/components.xml
       116 Tue Oct 30 22:16:06 GMT 2018 META-INF/maven/net.sigmalab.maven.plugins/jira-maven-plugin/pom.properties
      2228 Tue Oct 30 22:15:36 GMT 2018 net/sigmalab/maven/plugin/jira/formats/MarkDownGenerator.class
     30371 Tue Oct 30 22:15:44 GMT 2018 META-INF/maven/plugin.xml

By specifying the dependency upon fuego in the `<plugin>` section then maven will go away and retrieve that as part of it's build process as normal.

**Comment by schrepfler** [comment] 2018-10-30 22:37
A jar would not contain another jar by standard, it’s more likely maven handles the lifecycle of the component and the jar is referenced from the ~/.m2/repository cache and added to the classpath when running.

**Comment by dgrierso** [comment] 2018-10-30 22:40
Agreed ... but the issue is that one of the underlying Atlassian jar's which we use has a dependency upon the fuego jar. Consequently, the options are either to include the fuego jar in ours or have the dependency called out in the using `pom.xml`.

My thought was that the latter was the more appropriate approach.

Can you think of an alternative?

**Comment by tmortagne** [comment] 2018-10-31 09:21
I don't understand what is the problem exactly. If you add this in your `<dependencies>` with `<scope>runtime</scope>` it should behave the same as now except that the user of the plugin does not have anything to do. And yes Maven does not bundle anything (unless you explicitly use a special plugin to do that), it resolve dependencies transitively.

**Comment by dgrierso** [comment] 2018-10-31 09:56
Thanks for that ... wasn't aware that the `runtime` scope would operate like that upon a dependency to a maven plugin.

I've committed this on branch bugfix/59 - if you want to pull / test that on your code we should release that as 0.8.1 I think.

**Comment by tmortagne** [comment] 2018-10-31 10:04
Thanks !

What `runtime` scope mean is that it's not injected when building the code but it's injected at runtime.

**Comment by dgrierso** [comment] 2018-10-31 10:37
Yes, was aware of that -- where I've used it before was with Tomcat based applications which have had `servlet-api-<version>.jar` provided at runtime.

How it gets injected to a *maven-plugin* was what I didn't know about, as the "runtime" environment is actually a maven session and not an execution session.

If that works then great 👍 

As I said I reckon this should be merged and delivered as 0.8.1 rather than a full version upgrade - there's no specific change to the underlying functionality, it's just a change to the configuration mechanism.

**Comment by tmortagne** [comment] 2018-10-31 10:43
> How it gets injected to a maven-plugin was what I didn't know about, as the "runtime" environment is actually a maven session and not an execution session.

runtime scope here just means whatever is the context in which the code is executed, it's not really related to a specific Maven context. In short the only difference with all the other dependencies you have is just that you don't have it during the build.

**Comment by schrepfler** [comment] 2018-10-31 10:48
I can tag and release it today as 0.8.1. I’ll merge he branch and release if it’s done?

**Comment by schrepfler** [comment] 2018-11-03 01:42
Released to Nexus, thanks guys! :clap:

**Closed by schrepfler** 2018-11-03 01:42 UTC
Labels: dependencies

**Comment by schrepfler** [comment] 2023-11-30 11:39
As I'm trying to use this plugin internally it seems that fugue https://central.sonatype.com/artifact/io.atlassian.fugue/fugue 5.0 depends on fugue-parent which itself is not published on central so when we link to it and one only has central it'll fail to download that dependency. Atlassian seems to have butchered a bit the release and distribution process of this lib and hasn't refreshed it since 2022. I'm tempted to downgrade it to 4.7.2 or shade it on build.
